### ISSUE TITLE
Would love to see the content area scrollable when editing

### ISSUE THREAD

**Issue by mikebronner** [JacobFitzp/nova-canvas#1]
Without the editor being a fixed height and scrollable, it is pretty tedious to do various things while editing long documents and having to manipulate the toolbar. or perhaps make the toolbar sticky, without limiting the height of the editor? that might be a more elegant solution.

Thanks for this package!

**Comment by JacobFitzp** [comment]
Excellent suggestion, on it 🙂 

I think the best solution is to do both! Make the toolbar sticky, but also provide an optional `->scrollable(maxHeight)` option so it can be customised.
