### ISSUE TITLE
Reference a person or another resource

### ISSUE THREAD

**Issue by scramatte** [JacobFitzp/nova-canvas#10]
Hello,

In github editor, you can reference person using @  and a ticket using #  
![imagen](https://github.com/user-attachments/assets/1bd88f28-1fce-4adb-a3d7-9c82f9d0004e)

Does it possible to implement something similar ? 

Regards

**Comment by JacobFitzp** [comment]
This kind of ties into #7, you would be able to reuse that functionality for things like mentions.

**Comment by JacobFitzp** [comment]
Going to mark this as a duplicate and close it, but I will keep your requirements in mind.

Thanks 🙂
